name: hpo_inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<1.20
  - scipy
  - tqdm
  - tabulate
  - pandas
  - matplotlib
  - seaborn
  - pymc3<4.0
  - arviz
  - networkx
  - jupyterlab
  - pytest
  - pip
  - pip:
    - pre-commit
    - black
    - isort
    - flake8 