name: hpo_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - pip>=21.0
  - networkx >=3.1
  - tabulate>=0.9.0
  - pip:
    - tqdm>=4.60.0 